import type { Metadata } from "next";

import { Inter } from "next/font/google";
import "./globals.css";
import { RootLayoutProps } from "@/global/types";
import { Navbar } from "../components/Navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ordina Weather App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params }: RootLayoutProps) {
  return (
    <html lang={params.lang}>
      <body className={inter.className}>
        <Navbar lang={params.lang} />
        {children}
      </body>
    </html>
  );
}
